// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wilzafahgkvvifqpaqbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbHphZmFoZ2t2dmlmcXBhcWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTQ5ODQsImV4cCI6MjA2OTczMDk4NH0.oqY0Gf1ePDmuU298KHNLpEfpq0uApzcAQJrNwKN2gmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});